### ISSUE TITLE
Images including drop shadows

### ISSUE THREAD

**Issue by Gorcyn** [davidschreiber/FancyCoverFlow#10]
There is an annoying bug with images including drop shadows.

With this sample image for example :
https://dl.dropboxusercontent.com/s/da9c10jdtk4g0c0/98014_presentations-01.png

I used a vertical LinearLayout to contain an ImageView and a TextView.
Every time I scroll, the drop shadow of the image is like doubled, as if the Bitmap was drawn over the previous one at each call of the draw function.

I understand the problem but I can't find how to fix it.

**Comment by Gorcyn** [comment]
I found a way to let the view keep its render in cache... a comment dropped me an hint.
The application I'm working on targets 4.0+ (so are my tests devices) so I didn't tried to use the cache before the version test. 

```
@TargetApi(Build.VERSION_CODES.HONEYCOMB)
    @Override
    protected void dispatchDraw(Canvas canvas) {
        View childView = getChildAt(0);

        if (childView != null) {

            // If on honeycomb or newer, cache the view.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
                if (childView.isDirty() && !childView.isDrawingCacheEnabled()) {
                    childView.draw(this.wrappedViewDrawingCanvas);

                    // Edited by @Gorcyn
                    {
                        childView.setDrawingCacheQuality(View.DRAWING_CACHE_QUALITY_HIGH);
                        childView.setDrawingCacheEnabled(true);
                    }
                    if (this.isReflectionEnabled) {
                        this.createReflectedImages();
                    }
                }
            } else {
                childView.draw(this.wrappedViewDrawingCanvas);
            }
        }

        canvas.drawBitmap(this.wrappedViewBitmap, (this.getWidth() - childView.getWidth()) / 2, 0, this.paint);
    }
```

That could help!

**Comment by DjulLau** [comment]
Thanks a lot for this workaround !

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.
