### ISSUE TITLE
Excessive calls to getChildStaticTransformation

### ISSUE THREAD

**Issue by RPCarter53** [davidschreiber/FancyCoverFlow#15]
I have added a Log.e line into the getChildStsticTransformation and noticed that this routine is called continuously, many times a second, never stopping. Not exactly a loop as the App remains responsive, but obviously this would be a significant drain on device resources. I have found that the problem is resolved by commenting out the following:
    if (android.os.Build.VERSION.SDK_INT >= 16) {
//      item.invalidate();
    }

I am running on builds > 16 and yet I notice no visual difference after commenting as above. I do not use reflection. What exactly is the need for this additional invalidate?

Regards

Roy

**Comment by davidschreiber** [comment]
Hi Roy,

I haven't tried it on the newest KitKat build, but on Android versions that have hardware drawing activated by default, the Gallery widget had the bad habit of not refreshing the view after doing a transformation.

Also, I found this post of Romain Guy on this problem who also mentions calling `invalidate()` after transformation: https://code.google.com/p/android/issues/detail?id=35178

Probably, the behavior changed on KitKat? Would be great if you could look into this :+1 If you have time and fun :-)

**Comment by RPCarter53** [comment]
David,
 Yes we do see drawing issues on KitKat devices and emulators using GPU emulation. I will continue the investigation. I just wondered if you could imagine adjusting the placement of the invalidate() such that this apparent loop is avoided! 

I will also investigate turning off Hardware Emulation to see what impact the has.

Regards

Roy

**Comment by RPCarter53** [comment]
David,
    I think I have a resolution to this that works OK without repeated calls and without turning off Hardware Acceleration. In the link to Roman’s post it is mentioned there are comments referring to doing an invalidate in offsetChildrenLeftAndRight in Gallery but as this is private it would require duplication of Gallery. However offsetChildrenLeftAndRight calls offsetLeftAndRight on all its children and with FancyCoverFlow, all the children are of type FancyCoverGlowWrapper. By overriding offsetLeftAndRight in FancyCoverFlowWrapper, calling the super version and doing an invalidate() (see below) we seem to get the desired result without the draw loop. Obviously need to take out the call to invalidate in getChildStaticTransformation.

```
@Override
public void offsetLeftAndRight(int offset) {
super.offsetLeftAndRight(offset);
// required to get children to draw correctly without drawing loop
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.JELLY_BEAN) 
    invalidate();
}
```

Cheers

Roy

**Comment by rbarriuso** [comment]
I had the same problem on my app running on Android 4.1.2, but it seems to be fixed using Roy's code.

Thanks a lot!
  Rafa.

**Comment by totaltang** [comment]
Thanks, Roy!   great solution

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by Rflyee** [comment]
Thanks, Roy. it works well !

**Comment by jzeferino** [comment]
I know that the project is no longer maintained but anyone has a solution for this?
