### ISSUE TITLE
Image OnClickEvent

### ISSUE THREAD

**Issue by omershafiq** [davidschreiber/FancyCoverFlow#18]
if setOnClick Event is applied to image or view coverflow freezes

**Comment by EpicDraws** [comment]
This is really unfortunate. Has anyone fixed this issue?

**Comment by EpicDraws** [comment]
I was able to resolve this issue through handling taps myself in onInterceptTouchEvent and onTouchEvent. Glad to share if anyone is interested. The code isn't clean enough for a pull, but I will make it so if desired.

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by engr-erum** [comment]
@EpicDraws   can  u share project
