### ISSUE TITLE
Use multiple views as coverflow item

### ISSUE THREAD

**Issue by guyzk** [davidschreiber/FancyCoverFlow#19]
Is it possible to inflate a whole layout consisting of several views as a single coverflow item and set that layout in XML?
It would be nice to see such an example.

This is the view I wish to have as a single coverflow item.
Help appreciated!

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:layout_width="match_parent" android:layout_height="match_parent">
<ImageView
    android:id="@+id/positionViewIv"
    android:layout_width="150dp"
    android:layout_height="150dp"
    android:scaleType="fitCenter"
    android:src="@drawable/red_0"
    android:layout_centerInParent="true"/>
<LinearLayout
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:layout_centerInParent="true">
    <TextView
        android:id="@+id/positionViewTv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:text="BALANCE"/>
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:text="SUMMARY"/>
</LinearLayout>
```

</RelativeLayout>

**Comment by davidschreiber** [comment]
You can inflate your custom coverflow items and return them in `FancyCoverFlowAdapter::getCoverFlowItem()`. See the example in https://github.com/davidschreiber/FancyCoverFlow/blob/master/samples/src/at/technikum/mti/fancycoverflow/samples/example/ViewGroupExample.java#L83

Basically, all you need to do is something like `View item = LayoutInflater.from(context).inflate(R.layout.my_custom_view, viewGroup, false);` and return your view.

**Comment by guyzk** [comment]
I tried this:

```
    @Override
    public View getCoverFlowItem(int position, View reusableView, ViewGroup parent) {
        View root;

        if(reusableView==null){
            root = LayoutInflater.from(activity).inflate(R.layout.option_view_single, parent, false);
        }else{
            root = reusableView;
        }

        ImageView image = (ImageView)root.findViewById(R.id.positionViewIv);
        TextViewPlus text = (TextViewPlus)root.findViewById(R.id.positionViewTv);
        image.setImageResource(R.drawable.green_14);
        text.setText("You Win!!!");
        parent.setBackgroundColor(activity.getResources().getColor(R.color.green_opac));

        return root;
    }
```

but now i get only 1 item per page and i see the next only when i swipe left or right!
also the view isn't centered in it's parent which is what i need...
Can you give me some guidance??

**Comment by davidschreiber** [comment]
You will also need to set some size constraints to the child view like this

```
if(reusableView==null){
    root = LayoutInflater.from(activity).inflate(R.layout.option_view_single, parent, false);
    // Please calculate the size of your view, do not use pixel values (just an example)
    // (you will probably have to set at least height or width, or both)
    root.setLayoutParams(new FancyCoverFlow.LayoutParams(300, 600));
}else{
    root = reusableView;
}
```

**Comment by guyzk** [comment]
Perfect!!!!
I never got such a quick answer before.
Huge thumbs up!!
I do recommend to add this as an example as I believe it will help lot's of people.

**Comment by virenpurohit** [comment]
I want to cover my layouts full screen. what modification would give me the expected result.

**Comment by anasalabed** [comment]
@virenpurohit 
i hope you will find the answer in the link below : 
http://stackoverflow.com/questions/2868047/fullscreen-activity-in-android

**Comment by virenpurohit** [comment]
@anasalabed : That is not what I am talking about.

I want to simply increse the height of the view in above mentioned code? How can I. you will understand if and if you have used fancycoverflow example.

**Comment by engr-erum** [comment]
@guyzk  can u tell me its only showing one image once i click on image center then it should show atleast 2 or 3 images consecutive
