### ISSUE TITLE
Are those scenarios available

### ISSUE THREAD

**Issue by dimityrivanov** [davidschreiber/FancyCoverFlow#21]
1.Detect image click
2.Detect image long press
3.Detect top left corner click
4.Minimize the space between images

**Comment by bytebeats** [comment]
@mitko9000 
According my usage experience, the former two works well, the third, I didn't know what that means, And the last, I had the same question.

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by bytebeats** [comment]
@davidschreiber 
Are you working on that or, have you finished that? I mean the coverflow implemented by RecyclerView.

**Comment by davidschreiber** [comment]
No I am not working on this - but as the Gallery widget (which FancyCoverFlow is based on) was deprecated since ever, this would probably be the right way to go.
