### ISSUE TITLE
Move next and previous using buttons

### ISSUE THREAD

**Issue by rptts** [davidschreiber/FancyCoverFlow#22]
Hello,

I started using this library and I'm having some trouble in understanding how can I make the coverflow to go to specific item (and animate).
I was trying to force the click event on the item, but with no luck so far.
Is there an easy way to do this?
Thanks.

**Comment by emptyway** [comment]
since FancyCoverFlow is an extension of Gallery
i tried this

```
fancyCoverFlow.setSelection(currentPosition + 1, true);
```

it does change the current highlighted item, but the animation flag seems to be ignored.

**Comment by emptyway** [comment]
I found a hacky way to move back and forward animated 

the hack is to create an "MotionEvent" to simulate a swipe

override this on FancyCoverFlow.java

```
@Override
    public void setSelection(int position, boolean animate) {
        if (animate) {
            boolean isForwardScroll = getSelectedItemPosition() < position;

            Rect rect = new Rect();
            getHitRect(rect);

            int width = Math.abs(rect.width());
            if (!isForwardScroll) {
                width = width * -1;
            }
            int x = rect.centerX() + width / 2;
            int y = rect.centerY();

            MotionEvent event = MotionEvent.obtain(100, 100, MotionEvent.ACTION_DOWN, x, y, 0);
            onDown(event);
            onSingleTapUp(null);
        } else {
            super.setSelection(position, false);
        }
    }
```

**Comment by rptts** [comment]
Thanks, that helped :)

**Comment by engr-erum** [comment]
@simonlinj   i have images in fancyCoverFlow i just have to change current Item i.e. i want to set current position 0 how will i do ? isnot there any method already available in library

**Comment by Mahdiazadbar** [comment]
+1
also i have this problem. 
set selction don't move with animation

**Comment by pranaypatel512** [comment]
@Mahdiazadbar : same issue I am facing. @simonlinj : Can you help us?
