### ISSUE TITLE
Library have some  warning due to using deprecated API  and import issue 

### ISSUE THREAD

**Issue by pmishra0** [davidschreiber/FancyCoverFlow#23]
Library have some  warning due to using deprecated API  and import issue.
1. Using Gallery API which is depricated.
2. FancyCoverFlowItemWrapper is importing android.\* package  

Please help on above issue.

Thanks,
Prashant

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.
