### ISSUE TITLE
Use of negative setSpacing causes selection issues

### ISSUE THREAD

**Issue by DjulLau** [davidschreiber/FancyCoverFlow#28]
Hi,

I'm using a negative spacing (coverFlow.setSpacing(-200)) to achieve a certain look.
This works but creates item selection issues. For example if you touch the first item to the left it acts like if the second item was touched even if visually they don't overlap.

Is setSpacing the right way to reduce space between items ?

Thanks,

Julien

**Comment by aldefy** [comment]
Hi , any resolve or solutions that i missed reading here ..

**Comment by DjulLau** [comment]
Hi, not to my knowledge :-(

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by aldefy** [comment]
Ok thanks , will try to find solution if not make the switch as its , part of a client app im working on , will hit my delivery schedule
