### ISSUE TITLE
OOM Occurs..

### ISSUE THREAD

**Issue by asker517** [davidschreiber/FancyCoverFlow#31]
It's a very nice libray..

but when I use it and try to make the item not noly just ImageView...and then play it over and over..OOM Will Occurs...

for help...

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by yqyzxd** [comment]
I have same problem，why reuseableView always is null 。if show many image ，it will nom
