### ISSUE TITLE
getChildStaticTransformation(View child, Transformation t)  problem

### ISSUE THREAD

**Issue by bobingxin** [davidschreiber/FancyCoverFlow#32]
i am a chinese people,when getChildStaticTransformation(View child, Transformation t) do child invalidate will Overlap Wallpaper.you can use The gradient image do a test,will see my problem. i want to konw how to resolve this problem.

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.
