### ISSUE TITLE
How to get current position from fancycoverflow?

### ISSUE THREAD

**Issue by SakthivelA** [davidschreiber/FancyCoverFlow#34]
Hi, good library for this one but i have some issues, how can i get current position from this coverflow?. When i scroll to play with this, i need to get the center of child position. Please quick reply to this one.

Thanks in advance.

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by deepakrokz** [comment]
this.fancyCoverFlow.setOnItemSelectedListener(new OnItemSelectedListener() {

```
    @Override
    public void onItemSelected(AdapterView<?> parent, View view,
            int position, long id) {
         Log.d("fancyFlowCurPos ", String.valueOf(position));
    }

    @Override
    public void onNothingSelected(AdapterView<?> parent) {

    }
});
```

**Comment by shubham-infosys** [comment]
@SakthivelA  Hello. Have you found any solution this. Please let me know in case you are able to get the centre position node. Thanks in advance.
