### ISSUE TITLE
How to change default image position to display

### ISSUE THREAD

**Issue by yuan8421** [davidschreiber/FancyCoverFlow#37]
This library is awesome. But I have problem with default image position to display. I have an array image[] imgArr. By default, it always show imgArr[0]. Would you tell me how to change it to imgArr[1] or other? 

Many thanks!!

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by yuan8421** [comment]
Glad to receive your message! Well, I have found a way to solve this
problem. Great project BTW~

**Comment by reshma30** [comment]
Hi ! Thanks for replay..
But as i ve implement this lib in project can i get solution thought? it would be helpful.
and also I thank you for your suggestion , i would really like to use android default feature in application.

**Comment by engr-erum** [comment]
@reshma30   how u done ?

**Comment by davidschreiber** [comment]
This project is no longer maintained. Feel free to fork it and to improve upon it. Thanks!
