### ISSUE TITLE
lollipop weird behavior

### ISSUE THREAD

**Issue by cristiano939** [davidschreiber/FancyCoverFlow#41]
Hello David, 
I'm using this fancy cover flow in one of my projects at work, and find out a weird behavior, that maybe you can help me.
On Lollipop android version the fancy coverflow disapears with the selected item when the device is blocked and brought back again to the application.
Have any ideas?

**Comment by davidschreiber** [comment]
This project is no longer maintained. Feel free to fork it and to improve upon it. Thanks!
