### ISSUE TITLE
Scrolling is not Woking while custom adapter are used

### ISSUE THREAD

**Issue by pinkalmistry** [davidschreiber/FancyCoverFlow#45]
Hai,

While i am using the custom adapter at that time is works but while i am scrolling the view at that tiem it dosen't work. Scrolling is not done on the custom apapter view.

can you help me why is not working with the custom adapter?

**Comment by davidschreiber** [comment]
This project is no longer maintained. Feel free to fork it and to improve upon it. Thanks!
