### ISSUE TITLE
graddle build

### ISSUE THREAD

**Issue by liesel-zz** [davidschreiber/FancyCoverFlow#46]
Not find the repository, do you have any new link? 

https://android-arsenal.com/details/1/838

**Comment by Mehdiway** [comment]
I'm having the same problem. I can't add the project via

```
compile 'com.github.davidschreiber:FancyCoverFlow:0.1.1_b1'
```

With

```
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```

**Comment by Mehdiway** [comment]
On jitpack.io website :

> If the project doesn't have any GitHub Releases you can use the short commit hash or 'anyBranch-SNAPSHOT' as the version.

You can replace the release tag with the short commit hash, so I tried the following and it worked :

```
compile 'com.github.davidschreiber:FancyCoverFlow:a777f43'
```

**Comment by davidschreiber** [comment]
This project is no longer maintained. Feel free to fork it and to improve upon it. Thanks!
