### ISSUE TITLE
Coverflow presentation problem in landscape mode

### ISSUE THREAD

**Issue by pstuashiqcse** [davidschreiber/FancyCoverFlow#49]
Hey,

First of all thanks to developer to develop this awesome library.

I'm facing some problem in presenting coverflow in landscape mode. In default spacing [ this.setSpacing(0); ] covers showing with long distance. So, maximum 3 covers showing in landscape mode. But I wanna show at least five covers. So, I set a dynamic negative value [ this.setSpacing(x); here 'x' is a dynamic negative value depends on display size. i.e: -300 ]  to reduce spacing between covers. Its showing 5 covers perfectly but having some problem in swiping or selecting cover. I cant swipe left/right to immediate item, its forcefully transfers 2-3 items at once while swipe or select next/previous item. 

So, my question is:
1. can I solve the above problem using this.setSpacing(x);
2. Or Is there any efficient way to reduce space between covers

**Comment by davidschreiber** [comment]
This project is no longer maintained. Feel free to fork it and to improve upon it. Thanks!
