### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by mgursch** [davidschreiber/FancyCoverFlow#6]
I got a StackoverflowError with Android 2.3.x but not with Android 4.x. 

I do not have any idea whats the problem. 

Stacktrace: 
06-28 11:55:43.038: E/AndroidRuntime(30074): FATAL EXCEPTION: main
06-28 11:55:43.038: E/AndroidRuntime(30074): java.lang.StackOverflowError
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.widget.TextView.onDraw(TextView.java:3966)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6933)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at at.technikum.mti.fancycoverflow.FancyCoverFlowItemWrapper.dispatchDraw(FancyCoverFlowItemWrapper.java:200)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1380)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:7039)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.buildDrawingCache(View.java:6693)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.getDrawingCache(View.java:6481)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1571)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:831)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.View.draw(View.java:6936)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.widget.FrameLayout.draw(FrameLayout.java:357)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1904)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewRoot.draw(ViewRoot.java:1527)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewRoot.performTraversals(ViewRoot.java:1263)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1865)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-28 11:55:43.038: E/AndroidRuntime(30074):    at android.os.Looper.loop(Looper.java:123

**Comment by davidschreiber** [comment]
What devices did you use for testing? Did the sample application crash or some of your own apps? 

Thanks for the report.
