### ISSUE TITLE
Circular

### ISSUE THREAD

**Issue by kishorevaddadi07** [davidschreiber/FancyCoverFlow#7]
Hi , How can we make this overflow circular or infinite.

**Comment by davidschreiber** [comment]
Hi,

basically, you could try overriding the `FancyCoverFlowAdapter`'s `getCount()`, `getView()` methods to create more views than your data collection contains by doing a modulo operation and returning data from the front of your dataset. Further you can reset the `Gallery` position using an `OnItemSelectedListener` to some index in the back of your gallery if your user scrolls near the beginning of your data. I have not tried it yet but you could try this approach: http://abhinavasblog.blogspot.co.at/2011/09/android-infinite-looping-gallery.html

Probably I will implement an infinite example into the samples application.

Regards, David

**Comment by Shusshu** [comment]
I would also be interested in this :) +1

**Comment by geocine** [comment]
I am interested in this as well as I will be using this in a project any updates on this? Thanks david

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.

**Comment by engr-erum** [comment]
any solution of this issue  ? @davidschreiber  @geocine  @Shusshu

**Comment by Mahdiazadbar** [comment]
hi @davidschreiber 
if you have new version of FancyCoverFlow with recycle view please share it. thanks
