### ISSUE TITLE
Layout inflated in adapter is not moving anymore...

### ISSUE THREAD

**Issue by danysz** [davidschreiber/FancyCoverFlow#8]
Hi

I inflated an XML layout in adapter.
Now is I try to "slide" the covers nothing is happening if I am trying to do it touching the  items. If I slide from outside everything is fine...

Thanks

Daniel

**Comment by davidschreiber** [comment]
Hi daniel,

could it be that your inflated views consume the touch events? Probably they are also taking swipe gestures and take the events before they are passed to the coverflow?

**Comment by davidschreiber** [comment]
Sorry but I no longer maintain this project. I will still keep this project as reference for future visitors but I highly recommend to implement the coverflow itself using Android's new RecyclerView.
